### ISSUE TITLE
5: basic mood tracker

### ISSUE THREAD

**Issue by yishain11** [yishain11/burnout-preventor#5]

**Comment by yishain11** [comment]
DOD: 
in client:
- [ ] add a button at the end of each day to rank your happiness level
- [ ] after ranking, the data will be stored in mongodb (for start you can do in localstorage)
- [ ] when reloading the app the data will be presistant
