### ISSUE TITLE
6: basic mood tracker UI

### ISSUE THREAD

**Issue by yishain11** [yishain11/burnout-preventor#8]
DOD:
- [ ] add a page for viewing mood data
- [ ] add a chart to show the progress of mood as a function of time
- [ ] add ability to select start date and end date, and show the data between them
